### PR TITLE
Add -label command-line flag to label deployments

### PR DESCRIPTION
**Pull request by cristinaleonr**
1. Add new -label command line flag to identify deployments.

Example:

Command - ` go run ndt-server.go -ndt7_addr_cleartext=:8083 -label=machine-type=virtual -label=foo=bar`

JSON -
```JSON
"ServerMetadata":[{"Name":"foo","Value":"bar"},{"Name":"machine-type","Value":"virtual"}]
```

This will replace the `canary` boolean flag added under https://github.com/m-lab/ndt-server/pull/336, since it was not deployed to production.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/345)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/345)* status: 0 of 1 approvals obtained

___
*[ndt-server.go, line 139 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mul3WZs2GiVHucf6p-0:-Mul3WZs2GiVHucf6p-1:b-fosqto) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt-server.go#L139)):*
> ```Go
> func parseDeploymentLabels() {
> 	// Initially set labels to map to default values.
> 	labelsMap = map[string]string{"machine-type": "physical", "deployment": "stable"}
> ```

Now that I think about it, I'm not sure it makes sense to add default values here.

When the data reaches the pipeline, there will inevitably be some old data that doesn't follow these conventions and will be missing these values. We will have to deal with adding the appropriate values there, so that might be the better (and only) place to do so.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Thank you! Added some suggestions.

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/345#-:-MuldDCO9q4qWRKBa-p8:b-8d0x94)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[ndt-server, line 0 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mul_DgP2NUtAPzAX2G-:-Mul_DgP2NUtAPzAX2G0:bmmoucx) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt-server#L0)):*
This looks like a mistake. Please remove. Perhaps add to `.gitignore`?
___
*[ndt-server.go, line 47 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mul_jWc7oPLEl5TFwXH:-Mul_jWc7oPLEl5TFwXI:b-d5n840) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt-server.go#L47)):*
> ```Go
> 	dataDir           = flag.String("datadir", "/var/spool/ndt", "The directory in which to write data files")
> 	htmlDir           = flag.String("htmldir", "html", "The directory from which to serve static web content.")
> 	deploymentLabels  = flag.String("label", "", "Labels to identify the type of deployment.")
> ```

Please consider using https://pkg.go.dev/github.com/m-lab/go@v0.1.45/flagx#KeyValue rather than doing flag parsing in `ndt-server.go`

As currently available, this would require the same flag specified multiple times, i.e.

```
  -label=key1=value1
  -label=key2=value2
```

This seems very acceptable to me (maybe even with benefits to comma separated when it comes to config management). If you would prefer a KeyValueArray - then that could also be a fine addition to the m-lab/go/flagx package.
___
*[ndt-server.go, line 139 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mul3WZs2GiVHucf6p-0:-Mul_fqcAh4zQG4eFc01:b-mp0xzf) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt-server.go#L139)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Now that I think about it, I'm not sure it makes sense to add default values here.

When the data reaches the pipeline, there will inevitably be some old data that doesn't follow these conventions and will be missing these values. We will have to deal with adding the appropriate values there, so that might be the better (and only) place to do so.
</blockquote></details>

Default should be empty.
___
*[metadata/server.go, line 5 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-MulalTL9uQ6mqe--6vr:-MulalTL9uQ6mqe--6vs:bgwrw6q) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/metadata/server.go#L5)):*
> ```Go
> // ServerMetadata is a BigQuery-compatible type for deployment-specific
> // data under `ArchivalData`
> var ServerMetadata []NameValue
> ```

Is this a global variable?

Please consider how to pass this through to the structures accessible to the ndt5 and ndt7 servers created in main instead. (I regard the use of package globals in ETL is as an anti-pattern - I believe this would degrade the quality of the code here - I seem to feel strongly about this, so please let me know if you disagree strongly - there's probably something to learn either way).
___
*[ndt7/handler/handler.go, line 82 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-MulbzTN-IxzGWI9pAR3:-MulbzTN-IxzGWI9pAR4:bjqiks1) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt7/handler/handler.go#L82)):*
> ```Go
> 	// Collect most client metadata from request parameters.
> 	appendClientMetadata(data, req.URL.Query())
> 	data.ServerMetadata = metadata.ServerMetadata
> ```

I'm sure this can be passed by value through the Handler instance.
___
*[spec/data-format.md, line 42 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-MulczNr2FNRvlrH_avf:-MulczNr2FNRvlrH_avg:b-eb5cqp) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/spec/data-format.md#L42)):*
> ```Markdown
>         "ClientMeasurements": [
>         ],
>         "ClientMetadata": {
> ```

Oh, this type may be out of date... It was changed to the current form (array of structs) so that it would be BQ-compatible, b/c the "map"/"dict" form was not originally.
___
*[spec/data-format.md, line 76 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mulc7wQ4BMCWefwF6lh:-Mulc7wQ4BMCWefwF6li:b-gejmeb) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/spec/data-format.md#L76)):*
> ```Markdown
> ```JSON
> {
>   "machine-type": "virtual",
> ```

Is this really what it looks like? The type is an array of {Key, Value} structs.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/345)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @stephen-soltesz)

___
*[ndt-server, line  at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mul_DgP2NUtAPzAX2G-:-Muq9b_f4sQLvFVU1P8Z:b-sg81zx) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt-server#L)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This looks like a mistake. Please remove. Perhaps add to `.gitignore`?
</blockquote></details>

Thanks, removed!
___
*[ndt-server.go, line 47 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mul_jWc7oPLEl5TFwXH:-MuqA9qt8azUQYmugEdP:b-ggomkp) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt-server.go#L47)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please consider using https://pkg.go.dev/github.com/m-lab/go@v0.1.45/flagx#KeyValue rather than doing flag parsing in `ndt-server.go`

As currently available, this would require the same flag specified multiple times, i.e.

```
  -label=key1=value1
  -label=key2=value2
```

This seems very acceptable to me (maybe even with benefits to comma separated when it comes to config management). If you would prefer a KeyValueArray - then that could also be a fine addition to the m-lab/go/flagx package.
</blockquote></details>

Great suggestion. Updated to use `flagx.KeyValue`.
___
*[ndt-server.go, line 139 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mul3WZs2GiVHucf6p-0:-MuqA36-3YEiD1sFNjZX:b-8fx2u7) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt-server.go#L139)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Default should be empty.
</blockquote></details>

:+1: 
___
*[ndt7/handler/handler.go, line 82 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-MulbzTN-IxzGWI9pAR3:-Muq9z3zBTVgAv6lWNdR:b-896fix) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/ndt7/handler/handler.go#L82)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm sure this can be passed by value through the Handler instance.
</blockquote></details>

Done.
___
*[spec/data-format.md, line 42 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-MulczNr2FNRvlrH_avf:-Muq9wmPErKENG-PAhKZ:bjmumc0) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/spec/data-format.md#L42)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oh, this type may be out of date... It was changed to the current form (array of structs) so that it would be BQ-compatible, b/c the "map"/"dict" form was not originally.
</blockquote></details>

Updated to array.
___
*[spec/data-format.md, line 76 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mulc7wQ4BMCWefwF6lh:-Muq9v7cE7j0-TWeLMTS:bt2vr1b) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/spec/data-format.md#L76)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this really what it looks like? The type is an array of {Key, Value} structs.
</blockquote></details>

Fixed.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - if you would be willing to make one more edit to `spec/data-format.md` I would be grateful.

> Reviewed 1 of 10 files at r1, 9 of 12 files at r5, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/345#-:-MuqPBaoBn5ke2GAKjNQ:b-2fer1t)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[spec/data-format.md, line 42 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-MulczNr2FNRvlrH_avf:-MuqN8E6DlcKlanPeIMN:b-9755fn) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/spec/data-format.md#L42)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Updated to array.
</blockquote></details>

Thank you!
___
*[spec/data-format.md, line 76 at r4](https://reviewable.io/reviews/m-lab/ndt-server/345#-Mulc7wQ4BMCWefwF6lh:-MuqNERs--QY9r0gvxXR:b-luly) ([raw file](https://github.com/m-lab/ndt-server/blob/0590b4107fbeaf27db1f5b4e919dced3f617ea29/spec/data-format.md#L76)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

While we're here - would you be willing to fix the ClientMetadata example above also? (I believe it was me that originally failed to update these references when adjusting the structure to be BQ compatible -- so I'm sorry and thank you :) )

**Review by cristinaleonr — COMMENTED** [review]
Sure, done!

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/345#-:-MuqZAXBB3BO1RmJCkrM:b-1eh3wv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

**Comment by cristinaleonr** [comment]
Part of https://github.com/m-lab/etl/issues/1048.

**Pull request merged**
