### PR TITLE
Implement functionality to terminate ndt7 tests early given a client parameter 

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR implements functionality to terminate ndt7 download tests early when the client passes in an `early_exit` parameter in the request.

The changes were tested by running the server locally and making a request from [ndt7-client-go](https://github.com/m-lab/ndt7-client-go).

```
$ go run main.go -service-url ws://localhost/ndt/v7/download?early_exit=250
download in progress with localhost
Avg. speed  : 16630.5 Mbit/s
download: complete
         Server: localhost
         Client: 172.17.0.1
        Latency:     0.0 ms
       Download: 16630.5
         Upload:     0.0
 Retransmission:    0.12 %

$ go run main.go -service-url ws://localhost/ndt/v7/download?early_exit=200
download failed: websocket: bad handshake

download: complete
         Server: localhost
         Client:
        Latency:     0.0
       Download:     0.0
         Upload:     0.0
 Retransmission:    0.00
exit status 1
```

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/390)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/390)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`ndt7/download/sender/sender.go` line 21 at r1](https://reviewable.io/reviews/m-lab/ndt-server/390#-NYtizSS4JmRq7eRh5DT:-NYtifb79S6ELjz92NrU:b-cladkz) ([raw file](https://github.com/m-lab/ndt-server/blob/bc8630d4de552a1e6aaa11505c9c6a40cb1a1e06/ndt7/download/sender/sender.go#L21)):*
> ```Go
> // EarlyExitParams defines the parameters for the sender to end the
> // test early.
> type EarlyExitParams struct {
> ```

Please name this only `spec.Params`.
___
*[`ndt7/download/sender/sender.go` line 101 at r1](https://reviewable.io/reviews/m-lab/ndt-server/390#-NYtiQSB8cRkBcXnZyRY:-NYtiQSB8cRkBcXnZyRZ:bhts0g) ([raw file](https://github.com/m-lab/ndt-server/blob/bc8630d4de552a1e6aaa11505c9c6a40cb1a1e06/ndt7/download/sender/sender.go#L101)):*
> ```Go
> 			}
> 			// End the test once enough bytes have been acked.
> 			if params.IsEarlyExit && m.TCPInfo.BytesAcked >= params.MaxBytes {
> ```

I recommend additionally checking that TCPInfo is not nil.
___
*[`ndt7/handler/handler.go` line 261 at r1](https://reviewable.io/reviews/m-lab/ndt-server/390#-NYteyvW-p2fNLs9eZQd:-NYteyvW-p2fNLs9eZQe:b-fqvs4o) ([raw file](https://github.com/m-lab/ndt-server/blob/bc8630d4de552a1e6aaa11505c9c6a40cb1a1e06/ndt7/handler/handler.go#L261)):*
> ```Go
> 		}
> 
> 		value := values[0]
> ```

What happens if `early_exit=` is given?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/390)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`ndt7/download/sender/sender.go` line 21 at r1](https://reviewable.io/reviews/m-lab/ndt-server/390#-NYtizSS4JmRq7eRh5DT:-NYu73FuBDp_wq1oH2aD:b-896fix) ([raw file](https://github.com/m-lab/ndt-server/blob/bc8630d4de552a1e6aaa11505c9c6a40cb1a1e06/ndt7/download/sender/sender.go#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please name this only `spec.Params`.
</blockquote></details>

Done.
___
*[`ndt7/download/sender/sender.go` line 101 at r1](https://reviewable.io/reviews/m-lab/ndt-server/390#-NYtiQSB8cRkBcXnZyRY:-NYu74fp3LVsQV5gS3UE:b-896fix) ([raw file](https://github.com/m-lab/ndt-server/blob/bc8630d4de552a1e6aaa11505c9c6a40cb1a1e06/ndt7/download/sender/sender.go#L101)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend additionally checking that TCPInfo is not nil.
</blockquote></details>

Done.
___
*[`ndt7/handler/handler.go` line 261 at r1](https://reviewable.io/reviews/m-lab/ndt-server/390#-NYteyvW-p2fNLs9eZQd:-NYu75kFBLrwjNbCDXJ6:b-fbyo3e) ([raw file](https://github.com/m-lab/ndt-server/blob/bc8630d4de552a1e6aaa11505c9c6a40cb1a1e06/ndt7/handler/handler.go#L261)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What happens if `early_exit=` is given?
</blockquote></details>

It takes the parameter value as "", the condition below becomes true, and it returns an error. I added a test case for this.

This is also the output from the client:
```
$ go run main.go -service-url ws://localhost/ndt/v7/download?early_exit=
download failed: websocket: bad handshake

download: complete
         Server: localhost
         Client:
        Latency:     0.0
       Download:     0.0
         Upload:     0.0
 Retransmission:    0.00
exit status 1
```

**Review by stephen-soltesz — APPROVED** [review]
I'm sorry - I put a typo in my comment about `sender.Params`.

With that change :lgtm:

> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/390#-:-NYu9l1i6QKkDN5qHel1:bexaha2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`ndt7/download/sender/sender.go` line 21 at r1](https://reviewable.io/reviews/m-lab/ndt-server/390#-NYtizSS4JmRq7eRh5DT:-NYu9-VS3d_l7fRLND73:b-vyo0ws) ([raw file](https://github.com/m-lab/ndt-server/blob/bc8630d4de552a1e6aaa11505c9c6a40cb1a1e06/ndt7/download/sender/sender.go#L21)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm so sorry - I wrote `spec` but meant to leave it in the `sender` package. I just wanted the shorter type name. /shamecube me 

Would you please return the type definition to this package with the short name?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/390)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`ndt7/download/sender/sender.go` line 21 at r1](https://reviewable.io/reviews/m-lab/ndt-server/390#-NYtizSS4JmRq7eRh5DT:-NYuDllI4KaLKRp6Dr3N:b60r506) ([raw file](https://github.com/m-lab/ndt-server/blob/bc8630d4de552a1e6aaa11505c9c6a40cb1a1e06/ndt7/download/sender/sender.go#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm so sorry - I wrote `spec` but meant to leave it in the `sender` package. I just wanted the shorter type name. /shamecube me 

Would you please return the type definition to this package with the short name?
</blockquote></details>

Yes, done.

**Pull request merged**
