### PR TITLE
Adjusted run network to get NDT5 speed tests working

### PR DESCRIPTION
**Pull request by ryanrolds**
I wasn't able to get NDT5 tests working until I switched to using network=host as that exposes all ports bound by the container, not just the explicitly mapped/exposed ports. A side effect is that the service couldn't bind to 443 (possibly caused by the cap drop), updated to use 4443 instead.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/173)

### CODE REVIEW

**Comment by ryanrolds** [comment]
Why wouldn't you want to be able to run both at the same time? Having two different methods for running just complicates manually testing NDT7 and NDT5 quickly. The attempt of this PR is

**Comment by bassosimone** [comment]
They are different use cases. The one which is there works for ndt7 with minimal privileges (and addresses my use case of testing ndt7 without caring about ndt5), while your use case is more tailored towards ndt5 and would break my test case in that I need traffic on 443 when I do research on a ndt7 feature before landing it on this repo.

I understand that I could use iptables to redirect the traffic, however, I am not happy about adding additional hoops to jump into before being up to speed.

Can you test whether adding —cap-add=NET_ADMIN and —network=host is enough to allow for a deployment that works for both ndt7 and ndt5? In such case, then maybe we can recommend that as a least privilege way of running the container.

**Comment by ryanrolds** [comment]
In production how is it configured? Do both work?

**Comment by ryanrolds** [comment]
I assume in production it's using 443 but I bet NDT5 also work, which is what I'm after. I guess I don't view the ports being different as a significant issue it's probably just a configuration option (flag or env var) on the client. What I view as a major issue is not being able to quickly run each speed tests. All developers are lazy (especially myself) and we will skip steps if it's not something we can quickly do. Ideally, a developer's local environment would startup with everything working.

Considering we already had an NDT5 breaking change released, one that I was able to reproduce (at least on 50% of tests) in my local env once I setup `ntd-server` and pointed my local SUA env at it, I think it would make sense to side on making it easier to run NDT5 speed tests easily.

**Comment by bassosimone** [comment]
> In production how is it configured? Do both work?

I am not super familiar with how we do things in production. IIRC we are not actively working to reduce privileges, which was what I was after with this implementation here.

**Comment by bassosimone** [comment]
@ryanrolds I am not familiar with Docker compose, so I don't understand what working with that tool entails. As far as this PR is concerned, I understand that providing more than one command to run the server is non practical. Also, do I understand correctly that after your change the code is able to run without issues and without privileges (it seems so, but I haven't tested it)? If that is true, then, do you mind listing an `iptables` command to make sure we redirect port `443` to `4443` such that the server is still exposed on `443`? I like the idea of having a single command to do all and you're right that that is more practical, but I'd also like to keep `443` working as before.

**Comment by ryanrolds** [comment]
Docker Compose allows taking all the options/switches in the `docker run` and putting them in a single place (env vars are preferred, but switches work too). It also allows multiple services to t be defined in a single place. IMO, it's a must use and it really enables setting up microservices in Docker. Here is the SUA docker-compose.yml (https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/docker-compose.yaml). The SUA file isn't perfect, but it shows how it can be used. I have a mostly working docker-compose.yml working for ndt-server.

I will update the PR this evening. I may include the docker-compose.yml file I have mostly done.

**Comment by ryanrolds** [comment]
I will test with `NET_ADMIN` too. That may make the need for iptables moot. I have no objections to binding to 443.

**Comment by bassosimone** [comment]
Thanks!

**Comment by ryanrolds** [comment]
Update. I'm still working on this. My evenings have been busy with a course that ends this week.

**Comment by ryanrolds** [comment]
The main purpose of this PR was to make the project easier to set up for junior devs, but considering only Docker on Linux is supported that goal isn't possible. As much I think everyone should just use Linux, it's an unrealistic expectation. Closing the PR as it's not needed/useful.

**Pull request closed without merging**
