### PR TITLE
Make ndt7 work over cleartext

### PR DESCRIPTION
**Pull request by bassosimone**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/222)

### CODE REVIEW

**Comment by pboothe** [comment]
Please add an ndt7 http client to the tests in `ndt-server_test.go`

**Comment by bassosimone** [comment]
@pboothe done, please take a look!

**Comment by bassosimone** [comment]
@pboothe Done! The CI is currently broken because of changes in etl-gardener, AFAICT.

**Comment by pboothe** [comment]
https://github.com/m-lab/ndt-server/pull/253 removes the etl dependency. Once that is in, please rebase.

**Comment by bassosimone** [comment]
@pboothe done, please take another look?

**Pull request merged**
