### PR TITLE
chore: add go.mod and go.sum

### PR DESCRIPTION
**Pull request by bassosimone**
Allows one to build ndt-server with Go 1.16.

By default m-lab/go was at version 1.4 but that did not seem to be the
latest version and so I manually pinned to the latest version.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/328)

### CODE REVIEW

**Comment by RA80533** [comment]
It would be worth pinning the Docker image as well since `golang:alpine` corresponds to the latest version of Go.

**Comment by bassosimone** [comment]
@stephen-soltesz could you perhaps take a look at this PR? Would you also like for me to pin the docker image version?

**Review by stephen-soltesz — COMMENTED** [review]
@bassosimone thank you. Sorry I missed this PR earlier -- if you have permission to assign reviewers, that's the best way. I've also added ndt-server repo events to our slack integration so we'd see events like this easier in the future.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/328#-:-MXHc63J-TmUrF9xFQVU:b-kfu1c)* status: 0 of 1 approvals obtained

**Comment by bassosimone** [comment]
@stephen-soltesz thank you!

**Pull request merged**
