### PR TITLE
Update to golang 1.18

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the Dockerfile.local to use go1.18.

This is part of https://github.com/m-lab/dev-tracker/issues/735

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/375)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
*[`Dockerfile.local` line 1 at r1](https://reviewable.io/reviews/m-lab/ndt-server/375#-NApmbZO1FQB4RsSLCsp:-NApmbZO1FQB4RsSLCsq:bsyke54) ([raw file](https://github.com/m-lab/ndt-server/blob/7e0dd05bdd5cca8371075ac41cb9d61add8ff088/Dockerfile.local#L1)):*
> ```
> FROM golang:1.18-alpine3.14 as ndt-server-build
> ```

Can we use `golang:1.18` (instead of `golang:1.18-alpine3.14`) so we don't have to install `git`, `gcc`, etc. on the next line?

This is actually what I did for `dash`, `disco`, `uuid`, and `uuid-annorator`.

Also, per official Go documentation: `This variant is highly experimental, and not officially supported by the Go project (see golang/go#19938 for details).`  Details: https://hub.docker.com/_/golang

**Review by SaiedKazemi — COMMENTED** [review]
Please see my comment regarding `go:<version>-alpine` images.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/375#-:-NApnx1hCLuKlqvELcU9:b-qcs2e)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Comment by SaiedKazemi** [comment]
*[`Dockerfile.local` line 2 at r2](https://reviewable.io/reviews/m-lab/ndt-server/375#-NAps04oES3rDzwz32Ps:-NAps04oES3rDzwz32Pt:b-7cbscs) ([raw file](https://github.com/m-lab/ndt-server/blob/20679a8cc0e2ab69750eb8c2fdc4852c477f21eb/Dockerfile.local#L2)):*
> ```
> FROM golang:1.18 as ndt-server-build
> RUN apk add --no-cache git gcc linux-headers musl-dev openssl bash
> ```

Since you are using `golang:1.18`, you shouldn't need this line (and `apk` doesn't exist).

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/375)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
PTAL?

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/375#-:-NApsSui1GQ3eUKzlE-C:b-833305)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi and @stephen-soltesz)

___
*[`Dockerfile.local` line 1 at r1](https://reviewable.io/reviews/m-lab/ndt-server/375#-NApmbZO1FQB4RsSLCsp:-NApsF4L-Uefzz3kSYSD:bjrw6c0) ([raw file](https://github.com/m-lab/ndt-server/blob/7e0dd05bdd5cca8371075ac41cb9d61add8ff088/Dockerfile.local#L1)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Can we use `golang:1.18` (instead of `golang:1.18-alpine3.14`) so we don't have to install `git`, `gcc`, etc. on the next line?

This is actually what I did for `dash`, `disco`, `uuid`, and `uuid-annorator`.

Also, per official Go documentation: `This variant is highly experimental, and not officially supported by the Go project (see golang/go#19938 for details).`  Details: https://hub.docker.com/_/golang
</blockquote></details>

You're right. I'd forgotten about this. It turns out openssl and bash are already included in the golang:1.18 image. Fixed.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/375)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`Dockerfile.local` line 2 at r2](https://reviewable.io/reviews/m-lab/ndt-server/375#-NAps04oES3rDzwz32Ps:-NApsXomBBBd5wqZoCqZ:b-896fix) ([raw file](https://github.com/m-lab/ndt-server/blob/20679a8cc0e2ab69750eb8c2fdc4852c477f21eb/Dockerfile.local#L2)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Since you are using `golang:1.18`, you shouldn't need this line (and `apk` doesn't exist).
</blockquote></details>

Done.

**Review by SaiedKazemi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt-server/375#-:-NApzrxC248q10uMq8Mi:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
